GET http://localhost:3003/ping
content-type: application/json

###

# PUT  http://localhost:3003/actor/001
# content-type: application/json

# ###

# GET  http://localhost:3003/actor/female
# content-type: application/json